name: Build Azurite Image for Kinoite 42

on:
  schedule:
    - cron: '30 03 * * *'
  push:
  pull_request:

jobs:
  run-build:
    strategy:
      matrix:
        fedora_version: [42]
    name: Run
    secrets: inherit
    uses: ./.github/workflows/main.yml
    with:
      fedora_version: 42
      is_stable: false